sudo: false
language: go
services:
- "docker"
go:
- "1.10.3"
jobs:
  include:
  - stage: tests
    script:
    - make tests
  - stage: deploy
    script:
    - eval "$(ssh-agent -s)"
    - make add-ssh-key
    - make build
    - make docker-build-stable
    - make docker-push-stable
    - make deploy-stable
  - stage: deploy-staging
    script:
    - eval "$(ssh-agent -s)"
    - make add-ssh-key
    - make build
    - make docker-build-nightly
    - make docker-push-nightly
    - make deploy-staging
stages:
- tests
- build
- name: deploy
  if: branch = master
- name: deploy-staging
  if: branch = develop
