sudo: false
language: go
services:
- "docker"
cache:
  directories:
    - ${TRAVIS_HOME}/gopath/bin
    - ${TRAVIS_HOME}/gopath/pkg
go:
- "1.11.4"
jobs:
  include:
  - stage: lint
    script:
      - make lint-all
  - stage: tests
    script:
    - make tests
  - stage: deploy
    env: VERSION=stable
    script:
    - eval "$(ssh-agent -s)"
    - make add-ssh-key
    - make docker-build
    - make docker-push
    - make deploy
  - stage: deploy-staging
    env: VERSION=nightly
    script:
    - eval "$(ssh-agent -s)"
    - make add-ssh-key
    - make docker-build
    - make docker-push
    - make deploy
stages:
- lint
- tests
- build
- name: deploy
  if: branch = master
- name: deploy-staging
  if: branch = develop
