sudo: false
language: go
services:
- "docker"
go:
- "1.10.3"
jobs:
  include:
  - stage: tests
    script:
    - make tests
  - stage: deploy
    env: VERSION=stable
    script:
    - eval "$(ssh-agent -s)"
    - make add-ssh-key
    - make docker-build
    - make docker-push
    - make deploy

  - stage: deploy-staging
    env: VERSION=nightly
    script:
    - eval "$(ssh-agent -s)"
    - make add-ssh-key
    - make docker-build
    - make docker-push
    - make deploy
stages:
- tests
- build
- name: deploy
  if: branch = master
- name: deploy-staging
  if: branch = develop
